package com.example.neuroforge.service;

import com.example.neuroforge.dto.*;
import com.example.neuroforge.entity.*;
import com.example.neuroforge.mapper.BugMapper;
import com.example.neuroforge.repository.*;
import jdk.dynalink.linker.LinkerServices;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import java.nio.file.AccessDeniedException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@Service
public class BugService {
    @Autowired
    private UserRepository userRepository;
    @Autowired
    private OrganizationRepository organizationRepository;
    @Autowired
    private BugRepository bugRepository;
    @Autowired
    private TaskRepository taskRepository;
    @Autowired
    private TestCaseRepository testCaseRepository;
    @Autowired
    private BugMapper bugMapper;

    public BugCreateResponse createBug(BugCreateRequest createRequest) throws AccessDeniedException {
        String email = Objects.requireNonNull(SecurityContextHolder.getContext().getAuthentication()).getName();
        User qaEngineer = userRepository.findByEmail(email).orElseThrow(()-> new UsernameNotFoundException("User not found"));
        TestCase testCase = testCaseRepository.findById(createRequest.testCaseId()).orElseThrow(()-> new RuntimeException("Test case not found"));
        Task task = taskRepository.findById(createRequest.taskId()).orElseThrow(()-> new RuntimeException("Task not found"));
        Organization organization = organizationRepository.findById(qaEngineer.getOrganization().getId()).orElseThrow(()-> new RuntimeException("Organization not found"));

        if (!testCase.getQaEngineer().getId().equals(qaEngineer.getId())){
            throw new AccessDeniedException("This test case is generated by another QA");
        }

        if (!testCase.getOrganization().getId().equals(task.getOrganization().getId())){
            throw new RuntimeException("Test case and task must belong to same organization");
        }

        if (bugRepository.existsByTitleAndTestCaseAndTask(createRequest.title(), testCase, task)){
            throw new RuntimeException("Bug is already reported");
        }

        Bug bug = Bug.builder()
                .testCase(testCase)
                .task(task)
                .qaEngineer(qaEngineer)
                .organization(organization)
                .title(createRequest.title())
                .description(createRequest.description())
                .bugSeverity(createRequest.bugSeverity())
                .bugStatus(createRequest.bugStatus())
                .build();

        bugRepository.save(bug);
        return bugMapper.createBugDto(bug);
    }

    public BugCreateResponse getBugByIdAndTestCase(Long bugId, Long testCaseId){
        String email = Objects.requireNonNull(SecurityContextHolder.getContext().getAuthentication()).getName();
        User qaEngineer = userRepository.findByEmail(email).orElseThrow(()-> new UsernameNotFoundException("User not found"));
        TestCase testCase = testCaseRepository.findById(testCaseId).orElseThrow(()-> new RuntimeException("Test case not found"));
        Bug bug = bugRepository.findById(bugId).orElseThrow(()-> new RuntimeException("Bug report not found"));

        if (!qaEngineer.getId().equals(bug.getQaEngineer().getId())){
            throw new RuntimeException("You can't receive the bug report created by another QA");
        }
        if (!testCase.getTask().getId().equals(bug.getTask().getId())){
            throw new RuntimeException("Bug and test case must belong to same task");
        }
        return bugMapper.createBugDto(bug);
    }

    public List<BugCreateResponse> getAllBugOfTestCase(Long testCaseId){
        String email = Objects.requireNonNull(SecurityContextHolder.getContext().getAuthentication()).getName();
        User qaEngineer = userRepository.findByEmail(email).orElseThrow(()-> new UsernameNotFoundException("User not found"));
        TestCase testCase = testCaseRepository.findById(testCaseId).orElseThrow(()-> new RuntimeException("Test case not found"));
        if (!qaEngineer.getOrganization().getId().equals(testCase.getOrganization().getId())){
            throw new RuntimeException("You can't receive bug reports of another organization");
        }
        List<Bug> bugs = new ArrayList<>();
        bugs = bugRepository.getAllByTestCase(testCase);
        return bugs.stream()
                .map(bug -> BugCreateResponse.builder()
                        .id(bug.getId())
                        .title(bug.getTitle())
                        .description(bug.getDescription())
                        .bugStatus(bug.getBugStatus())
                        .bugSeverity(bug.getBugSeverity())
                        .build()).toList();
    }

    public UpdateBugStatus updateBugStatus(Long bugId, UpdateBugStatus updateBugStatus){
        String email = Objects.requireNonNull(SecurityContextHolder.getContext().getAuthentication()).getName();
        User qaEngineer = userRepository.findByEmail(email).orElseThrow(()-> new UsernameNotFoundException("User not found"));
        Bug bug = bugRepository.findById(bugId).orElseThrow(()-> new RuntimeException("Bug report not found"));
        if (!qaEngineer.getId().equals(bug.getQaEngineer().getId())){
            throw new RuntimeException("You can't modify the status of bug report created by another QA");
        }
        if (!qaEngineer.getOrganization().getId().equals(bug.getOrganization().getId())){
            throw new RuntimeException("You can't modify the status of bug report of another organization");
        }
        bug.setBugStatus(updateBugStatus.bugStatus());
        bugRepository.save(bug);
        return UpdateBugStatus.builder()
                .bugStatus(bug.getBugStatus())
                .build();
    }

    public UpdateBugSeverity updateBugSeverity(Long bugId, UpdateBugSeverity bugSeverity){
        String email = Objects.requireNonNull(SecurityContextHolder.getContext().getAuthentication()).getName();
        User qaEngineer = userRepository.findByEmail(email).orElseThrow(()-> new UsernameNotFoundException("User not found"));
        Bug bug = bugRepository.findById(bugId).orElseThrow(()-> new RuntimeException("Bug report not found"));
        if (!qaEngineer.getId().equals(bug.getQaEngineer().getId())){
            throw new RuntimeException("You can't modify severity of bug report created by another QA");
        }
        if (!qaEngineer.getOrganization().getId().equals(bug.getOrganization().getId())){
            throw new RuntimeException("You can't modify the severity of bug report of another organization");
        }
        bug.setBugSeverity(bugSeverity.bugSeverity());
        bugRepository.save(bug);
        return UpdateBugSeverity.builder()
                .bugSeverity(bug.getBugSeverity())
                .build();
    }

    public void deleteBugReport(Long bugId){
        String email = Objects.requireNonNull(SecurityContextHolder.getContext().getAuthentication()).getName();
        User qaEngineer = userRepository.findByEmail(email).orElseThrow(()-> new UsernameNotFoundException("User not found"));
        Bug bug = bugRepository.findById(bugId).orElseThrow(()-> new RuntimeException("Bug report not found"));
        if (!qaEngineer.getId().equals(bug.getQaEngineer().getId())){
            throw new RuntimeException("You can't delete the bug report created by another QA");
        }
        if (!qaEngineer.getOrganization().getId().equals(bug.getOrganization().getId())){
            throw new RuntimeException("You can't delete the bug report of another organization");
        }

        bugRepository.delete(bug);
    }

}
